#!/bin/sh
#
### BEGIN INIT INFO
# Provides:		geth
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	Start and stop the geth daemon
### END INIT INFO
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/geth
NAME=geth
DESC="Geth Node"
PIDFILE=/var/run/geth.pid


start() {
	echo -n "Starting $DESC: "
	mount -o remount,size=90% /var/volatile
	start-stop-daemon -S -p $PIDFILE -N -10 -b -a /bin/sh -- -c "exec ${DAEMON} \
        --mainnet \
		--datadir=/persistent/geth \
		--metrics \
		--metrics.expensive \
		--metrics.addr=0.0.0.0 \
		--metrics.port=6061 \
		--http \
		--http.api="eth,net,web3" \
		--http.corsdomain=* \
		--http.addr=0.0.0.0 \
		--http.port=8545 \
		--http.vhosts=* \
		--authrpc.jwtsecret=/var/volatile/jwtsecret \
		--authrpc.vhosts=* \
		2>&1 | tee /var/log/geth.log"
	echo "$NAME."
}

stop() {
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
}
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
exit 0