#!/bin/sh
#
### BEGIN INIT INFO
# Provides:		nethermind
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	Start and stop the nethermind daemon
### END INIT INFO
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/dotnet/nethermind/nethermind
NAME=nethermind
DESC="Nethermind Node"
PIDFILE=/var/run/nethermind.pid
LOGFILE=/tmp/nethermind.log

get_cli_args() {
	local args=""
	[ -n "$NETHERMIND_METRICSCONFIG_ENABLED" ] && args+=" --Metrics.Enabled '$NETHERMIND_METRICSCONFIG_ENABLED'"
	[ -n "$NETHERMIND_METRICSCONFIG_INTERVALSECONDS" ] && args+=" --Metrics.IntervalSeconds '$NETHERMIND_METRICSCONFIG_INTERVALSECONDS'"
	[ -n "$NETHERMIND_METRICSCONFIG_NODENAME" ] && args+=" --Metrics.NodeName '$NETHERMIND_METRICSCONFIG_NODENAME'"
	[ -n "$NETHERMIND_METRICSCONFIG_PUSHGATEWAYURL" ] && args+=" --Metrics.PushGatewayUrl '$NETHERMIND_METRICSCONFIG_PUSHGATEWAYURL'"
	echo "$args"
}

start() {
	if [ -f /etc/json-config ]; then
		# Provides ATTESTATION_PROVIDER_URL
		source /etc/json-config
	else 
		echo "No json-config found"
	fi
	
	echo -n "Waiting for lighthouse to start... "
	while ! pgrep lighthouse > /dev/null; do
		sleep 1
	done
	echo "Lighthouse started."

	sleep 10

	source /etc/nethermind.conf
	ulimit -n 100000

	cli_args=$(get_cli_args)

	echo -n "Starting $DESC: "
	start-stop-daemon -S -p $PIDFILE -N -10 -b -a /bin/sh -- -c "exec ${DAEMON} \
		--config $NODE_NETWORK \
		-dd /persistent/nethermind \
		--JsonRpc.JwtSecretFile /opt/dotnet/nethermind/jwt-secret \
		--JsonRpc.Host 0.0.0.0 \
		$cli_args \
		2>&1 | tee ${LOGFILE}"
	echo "$NAME."
}

stop() {
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
}
case "$1" in
  start)
		start
		;;
  stop)
		stop
		;;
  restart|reload)
		stop
		start
		;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
exit 0
